// Centralized Giwi dialogue (docs/MASCOT.md §dialogue). Source strings double as i18n
// keys via the app's t(); localization lands in the locale packs like every other string.
export const DIALOGUE = {
  welcomeTitle: 'Welcome to MiGym',
  welcomeLine: 'Hi! I’m Giwi — I’ll help you set MiGym up for you.',
  start: 'Start',
  skip: 'Skip',
  askLang: 'What language do you prefer?',
  askName: 'First, what’s your name?',
  yourName: 'Your name',
  niceToMeet: 'Nice to meet you, {0}!',
  askAge: 'How old are you?',
  age: 'Age',
  askWeight: 'What do you weigh right now?',
  currentWeight: 'Current weight',
  askHeight: 'What’s your height?',
  height: 'Height',
  askGoal: 'What’s your main goal?',
  askGoalMulti: 'What are your goals? Pick as many as you like.',
  askExperience: 'What’s your experience level?',
  askDays: 'How many days per week can you train?',
  askSupps: 'Do you take any supplements? I’ll remind you every day.',
  yourProfile: 'Your profile',
  confirmProfile: 'Confirm',
  editProfile: 'Edit',
  perfectLine: 'Perfect! I know a little about you now.',
  tourLine: 'Now I’ll show you how MiGym works.',
  years: 'years',
  letsGo: 'Let’s go!',
}
